Fixed it

diff --git a/.github/workflows/python-publish.yml b/.github/workflows/python-publish.yml
--- a/.github/workflows/python-publish.yml
+++ b/.github/workflows/python-publish.yml
@@ -30,14 +30,22 @@ jobs:
     - name: Clean previous builds
       run: rm -rf dist
 
+    - name: Check if version exists
+      id: check_version
+      run: |
+        echo "CURR_VERSION=1.0.2"
+        echo "VERSION=$(python setup.py --version)"
+        pip install --upgrade pip
+        if "$CURR_VERSION == $VERSION"
+          echo "Version already exists. Aborting now..."
+          exit 1
+        fi
+
     - name: Build package
       run: python setup.py sdist bdist_wheel
 
     - name: Publish package to PyPI
-      if: always()
       env:
         TWINE_USERNAME: __token__
         TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
       run: twine upload --verbose dist/*
-    - if: failure()
-      run: echo "Version already exists. Aborting ..."
